### ISSUE TITLE
Toast not appearing in full screen mode

### ISSUE THREAD

**Issue by shahan007** [snakesilk/react-fullscreen#96]
I am using ANTD as my UI  library and following are the issues I have encountered so far as I have just started using it

- Toast notification are not appearing in the full screen mode.
- Popovers too are not appearing in the full screen mode
- Scrolling wasnt working but the workaround in https://github.com/snakesilk/react-fullscreen/issues/78 resolved it

**Comment by pomle** [comment]
This is probably not related to this library, as it only tells the browser what element should go full screen.

If toasts or other peripheral UI element are not working in fullscreen it is likely because they don't support fullscreen mode, or that they have been applied to an element outside the fullscreen element.

**Comment by Dilshan97** [comment]
> * Scroller  not working  in fullscreen mode #78

I'm also faceing same issue
